version: "3"
   
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zarina

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command:  python manage.py runserver 0.0.0.0:8000
              
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zarina
    container_name: django_first_docker_container
    depends_on:
      - db
      
volumes:
  postgres_data:
   