# Generated by Django 4.0.6 on 2022-07-29 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_action',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
