# Generated by Django 4.0.6 on 2022-07-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='user',
        ),
        migrations.AddField(
            model_name='visits',
            name='visits',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
