# Generated by Django 4.0.6 on 2022-07-31 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_visits_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayNumber',
        ),
        migrations.DeleteModel(
            name='VisitsCount',
        ),
    ]
