# Generated by Django 4.0.6 on 2022-08-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='user',
        ),
    ]
