# Generated by Django 4.0.6 on 2022-08-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_visits_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='all_count',
            field=models.IntegerField(default=0),
        ),
    ]
