# Generated by Django 4.0.6 on 2022-08-02 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_visits_all_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 8, 2, 10, 33, 48, 417459)),
        ),
    ]
