# Generated by Django 4.0.6 on 2022-08-02 19:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_visits_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 8, 2, 19, 24, 47, 703041, tzinfo=utc)),
        ),
    ]
