# Generated by Django 4.0.6 on 2022-08-03 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_visits_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='day',
        ),
        migrations.AlterField(
            model_name='visits',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 8, 3, 12, 57, 10, 837172, tzinfo=utc)),
        ),
    ]
