# Generated by Django 4.0.6 on 2022-08-04 16:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_user_count_remove_user_day_alter_visits_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='visits',
            name='day',
            field=models.DateField(default=datetime.datetime(2022, 8, 4, 16, 59, 58, 557998, tzinfo=utc)),
        ),
    ]
